import { QuizCardProps } from '@/components/QuizCardDifficulty'

export const quizzesDifficulty: QuizCardProps[] = [
  {
    id: '1',
    imageSrc: '/placeholder.webp',
    difficulty: 'Easy',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 1.5,
    category: 'General',
    duration: 10,
    title: 'General Knowledge Basics',
    players: 15,
    spotsAvailable: 85,
    totalSpots: 100
  },
  {
    id: '2',
    imageSrc: '/placeholder.webp',
    difficulty: 'Medium',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 2.5,
    category: 'Entertainment',
    duration: 8,
    title: 'Pop Culture Essentials',
    players: 60,
    spotsAvailable: 40,
    totalSpots: 100
  },
  {
    id: '3',
    imageSrc: '/placeholder.webp',
    difficulty: 'Medium',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 3.5,
    category: 'Science',
    duration: 12,
    title: 'Science for Beginners',
    players: 90,
    spotsAvailable: 10,
    totalSpots: 100
  },
  {
    id: '4',
    imageSrc: '/placeholder.webp',
    difficulty: 'Hard',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 1.0,
    category: 'Sports',
    duration: 10,
    title: 'Sports Fundamentals',
    players: 40,
    spotsAvailable: 60,
    totalSpots: 100
  },
  {
    id: '5',
    imageSrc: '/placeholder.webp',
    difficulty: 'Easy',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 1.0,
    category: 'Sports',
    duration: 10,
    title: 'Sports Fundamentals',
    players: 40,
    spotsAvailable: 60,
    totalSpots: 100
  },
  {
    id: '6',
    imageSrc: '/placeholder.webp',
    difficulty: 'Easy',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 1.0,
    category: 'Sports',
    duration: 10,
    title: 'Sports Fundamentals',
    players: 40,
    spotsAvailable: 60,
    totalSpots: 100
  },
  {
    id: '7',
    imageSrc: '/placeholder.webp',
    difficulty: 'Easy',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 1.0,
    category: 'Sports',
    duration: 10,
    title: 'Sports Fundamentals',
    players: 40,
    spotsAvailable: 60,
    totalSpots: 100
  },
  {
    id: '8',
    imageSrc: '/placeholder.webp',
    difficulty: 'Easy',
    authorAvatarSrc: '/avatarPlaceholder.webp',
    authorName: 'Alex Smith',
    reward: 1.0,
    category: 'Sports',
    duration: 10,
    title: 'Sports Fundamentals',
    players: 40,
    spotsAvailable: 60,
    totalSpots: 100
  }
]
